### ISSUE TITLE
using it with redux-persist

### ISSUE THREAD

**Issue by jasan-s** [stereobooster/react-snap#6] opened 2017-10-23 12:21 UTC
I was using `React-snapshot` was I am unable to use it with `redux-persist` because the following code which renders main app only after the redux store has been re-hydrated using `redux-persist`: 

```
import {render as snapshotRender} from 'react-snapshot'
import {ConnectedRouter} from 'react-router-redux'

async function init() {
const store = await configureStore()
snapshotRender(
  <Provider store={store}>
    {/* ConnectedRouter will use the store from Provider automatically */}
    <ConnectedRouter history={history}>
      <App />
    </ConnectedRouter>
  </Provider>,
  document.getElementById('root')
)
}

registerServiceWorker()
init()
```

I get the error that react-snapshot render was never called. Will this lib work within async function like above ?

**Comment by stereobooster** [comment] 2017-10-23 19:20
To be honest I don't know. Theoretically, it should work with anything, because there is real browser behind the scene.

Can you give it a try? It is few lines of config

**Comment by stereobooster** [comment] 2017-10-23 20:15
Maybe something like this https://github.com/geelen/react-snapshot/pull/46/files required. But I will need example to implement it

**Comment by jasan-s** [comment] 2017-10-23 21:05
@stereobooster  do you mean a example for a project? if so here is a github project  https://github.com/jasan-s/reactstarterwithcreatereactapp

**Comment by stereobooster** [comment] 2017-10-23 21:44
it seems to be working https://github.com/jasan-s/reactstarterwithcreatereactapp/pull/1

**Comment by jasan-s** [comment] 2017-10-23 22:13
@stereobooster  I am getting an error: 

```
/signUp/ log: rehydration complete
/faq/ log: rehydration complete
/ log: rehydration complete
/faq/ log: Render function authed:
/signUp/ log: Render function authed:
/ log: Render function authed:
/signIn/ log: rehydration complete
/signIn/ log: Render function authed:
/faq/ log: User Already Loggedin:
/ log: User Already Loggedin:
/ log: Content is cached for offline use.
/signUp/ log: User Already Loggedin:
/signIn/ log: User Already Loggedin:
Crawled 1 out of 6 (/)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\coding_projects\reactstarterwithcreatereactapp\build\faq\.html'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at saveAsHtml (E:\coding_projects\reactstarterwithcreatereactapp\node_modules\react-snap\index.js:196:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by stereobooster** [comment] 2017-10-23 22:55
the above issue is about windows paths. It was fixed in v0.5.4

**Closed by stereobooster** 2017-10-23 22:55 UTC

**Comment by piotr-cz** [comment] 2018-01-03 13:19
I've got the same problem, the Redux-persist PersistGate component was stuck in the [bootstrapping state](https://github.com/rt2zz/redux-persist/blob/v5.4.0/src/integration/react.js#L37).
I'm not really sure exactly where the problem is (maybe it's adding but not removing `bootstrapped` flag in state).

As redux-persist is responsible to maintain the state, I've decided to not add any references to state (opposite to what's suggested in Readme: [Redux section](https://github.com/stereobooster/react-snap/blob/v1.8.0/Readme.md#redux).
No more reading and saving in `window.__PRELOADED_STATE__` object seems to fix the problem

**Comment by stereobooster** [comment] 2018-01-03 13:30
You are realizing that if you do not save state in `window.__PRELOADED_STATE__` and you have some prerendered html as soon as application will boot in clients browser (which does not have any state in `localStorage`) it will erase all prerendered html and render state which corresponds to empty (redux) state?

Maybe something like this will help:
```js
const store = createStore(counterApp, stateFromLocalStorage || preloadedState || initialState)
```

**Comment by piotr-cz** [comment] 2018-01-03 13:43
Yeah, I've just realized that.
Browser is showing Prerendered page, then loading spinner and Application with retrieved state.

The problem is that final value of stateFromLocalStorage is not known at the moment of creating store as it's retrieved async (via IndexedDB). That's why Redux-persist is using bootstrapped flag.

**Comment by stereobooster** [comment] 2018-01-03 13:47
You can trick `react-snap` to generate html with spinner. E.g. stop application before it will fetch actual data so redux store would have something like `{ state: "loading" }`. You can detect `react-snap` via `navigator.userAgent === "ReactSnap"`

**Comment by piotr-cz** [comment] 2018-01-03 15:15
For spinner, I can use just Redux-persist library until it loads async state.
Actually problem is that it's not possible to use that library without a spinner - ie. showing html prerendered with react-snap. You need to show custom component which replaces any root element children ([PersistGate](https://github.com/rt2zz/redux-persist/blob/v5.4.0/docs/PersistGate.md) docs, [PersistGate.render](https://github.com/rt2zz/redux-persist/blob/v5.4.0/src/integration/react.js#L53-L55) src)

Anyway thank you for suggestions

**Comment by piotr-cz** [comment] 2018-01-04 11:04
Redux-persist adds a flag to state (`_persist.rehydrated = true`) so when Application is rendered with ReactDOM.hydrate, Redux-persist doesn't hydrate the state and PersistGate is locked in loading state.

To fix it switching the flag isn't enough, you have to remove whole `_persist` object

```js
window.snapSaveState = () => ({
  __PRELOADED_STATE__: {
    ...store.getState(),
    _persist: undefined
  }
})
```

It's also possible to remove `_persist` object after reading preloadedState from global object but then it's set by Redux-persist and saved as __PRELOADED_STATE__
