### ISSUE TITLE
Is it possible to ignore a file from being crawled? 

### ISSUE THREAD

**Issue by jamez14** [stereobooster/react-snap#88] opened 2018-01-01 17:24 UTC
First off, thanks for a great project! I just started using it but see immense value for some web apps I am working on.

Is there an option to ignore a file? I'm receiving a strange error as it appears to be doing something with a `pdf` file in my directory. I was hoping/wondering if "ignoring" this file would help solve the error.

```
$ react-snap
✏️  / log: Content is cached for offline use.
🕸  (1/6) /
⚠️  404 page title does not contain "404" string
🕸  (2/7) /404.html
🕸  (3/7) /story
🕸  (4/7) /info
🕸  (5/7) /how-to
🔥  /images/map.pdf Error: EEXIST: file already exists, mkdir '/Users/james/Sites/webapp/client/build/images/map.pdf'
🕸  (7/7) /accept
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also for what it's worth, all the routes live in `src/pages/route_folder/index.js` and the images/pdfs live in `public/images/image_name.png`.

**Comment by stereobooster** [comment] 2018-01-01 17:38
I suppose `react-snap` should check that the given link is the file (except `.html`) and it exists in the file system and ignore those files for crawling

**Comment by stereobooster** [comment] 2018-01-01 18:59
fixed in v1.8.0

**Closed by stereobooster** 2018-01-01 18:59 UTC
Labels: bug

**Comment by MEmmanuel** [comment] 2018-03-16 08:33
@stereobooster 
Hi !
I came across the same bug here.
But the issue is caused by the homepage setting.

The issue (in my case):     homepage: "/static/app"

> 🔥  /static/app/documents/doc.docx Error: EEXIST: file already exists, mkdir '.../app/build/documents/doc.docx'

in src/puppeteer_utils.js :
```
if (ext !== ".html" && ext !== "") {
  const filePath = path.join(sourceDir, routePath);
  skipExistingFile = fs.existsSync(filePath);
}
```
--->
```
if (ext !== ".html" && ext !== "") {
  const filePath = path.join(sourceDir, routePath.split(publicPath)[1]);
  skipExistingFile = fs.existsSync(filePath);
}
```

Do you want me to PR ?
Thx !

**Comment by stereobooster** [comment] 2018-03-16 21:48
Hi @MEmmanuel, can you share your config, I'm not sure how you get into this issue

**Comment by MEmmanuel** [comment] 2018-03-19 16:21
Hi @stereobooster,
Here is my package.json:
```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.17.1",
    "material-ui": "^1.0.0-beta.23",
    "material-ui-icons": "^1.0.0-beta.17",
    "mdi-material-ui": "^3.0.0",
    "react": "^16.2.0",
    "react-cookie-banner": "^3.0.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-document-meta": "^2.1.2",
    "react-dom": "^16.1.1",
    "react-ga": "^2.4.0",
    "react-loadable": "^5.3.1",
    "react-mixpanel": "0.0.9",
    "react-responsive": "^4.0.3",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.17",
    "smoothscroll-polyfill": "^0.4.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "postbuild": "react-snap",
    "test": "jest",
    "eject": "react-scripts eject",
    "flow": "flow",
    "flow-coverage": "flow-coverage-report"
  },
  "homepage": "/static/app",
  "proxy": "http://localhost:8123",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-jest": "^22.0.3",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "flow-bin": "^0.61.0",
    "flow-coverage-report": "^0.4.0",
    "jest": "^22.0.1",
    "react-snap": "github:MEmmanuel/react-snap",
    "react-test-renderer": "^16.2.0",
    "regenerator-runtime": "^0.11.1"
  },
  "flow-coverage-report": {
    "includeGlob": [
      "src/**/*.js"
    ],
    "excludeGlob": [
      "**/_*.js",
      "src/pages/about/**",
      "src/registerServiceWorker.js"
    ],
    "type": [
      "text",
      "html",
      "json"
    ]
  },
  "jest": {
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js"
    }
  },
  "reactSnap": {
    "puppeteerArgs": [
      "--no-sandbox"
    ],
    "include": [
      "/../../"
    ],
    "port": 45680
  }
}

```
I could remove port, it was for testing purpose...

**Comment by stereobooster** [comment] 2018-03-19 17:30
```
    "include": [
      "/../../"
    ],
```

include is path from URI, so I'm not sure what you want to accomplish here. Shouldn't it be `/static/app` or `/`?

**Comment by MEmmanuel** [comment] 2018-03-19 17:49
Mmm. Ok maybe my config is strange but:

Snap first come to homepage, so `/static/app` here. But my router is looking for `/`
So snap discover nothing, so I added `/../../` to eliminate `/static/app`.
Can't remember why and if simple `/` would work..

**Comment by stereobooster** [comment] 2018-03-19 17:52
`react-snap` uses `/static/app`, because of `"homepage": "/static/app",` it is done to mimic CRA behaviour

**Comment by MEmmanuel** [comment] 2018-03-19 18:11
Sorry CRA ?

**Comment by jamez14** [comment] 2018-03-19 18:12
@MEmmanuel CRA = [create-react-app](https://github.com/facebook/create-react-app/)

**Comment by MEmmanuel** [comment] 2018-03-19 18:21
o! ok thx @jamez14  :+1: 
Yes, CRA add homepage to path to get bundle files which is what I intended to do, because my app is hosted here. But my routing begins at root `/` so the routing can't match homepage.
Not sure I'm clear...

**Comment by stereobooster** [comment] 2018-03-19 19:10
try

```
  "reactSnap": {
    "puppeteerArgs": ["--no-sandbox"],
    "port": 45680,
    "publicPath": "/"
  }
```

**Comment by MEmmanuel** [comment] 2018-03-20 11:36
Yes, it's working fine actually. :)

But still, if I remove `.split(publicPath)[1])` in `puppeteer_utils.js` I get the error:
`🔥  /static/app/documents/doc.docx { Error: EEXIST: file already exists, mkdir '/.../app/build/documents/doc.docx'
    at Object.fs.mkdirSync (fs.js:909:18)
    at Function.sync (/.../node_modules/mkdirp/index.js:71:13)
    at saveAsHtml (/.../node_modules/react-snap/index.js:442:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/.../app/build/documents/contrat_location_logement_fonction.docx' }
`

Might be caused by the .docx extension ?

**Comment by stereobooster** [comment] 2018-03-20 11:41
@MEmmanuel try to create minimal reproducible example
