### ISSUE TITLE
when i remove service worker, react-snap say  Navigation Timeout Exceeded: 30000ms exceeded

### ISSUE THREAD

**Issue by mehrdadkhan64** [stereobooster/react-snap#203] opened 2018-06-25 09:33 UTC
🔥  / Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (C:\...\node_modules\puppeteer\lib\NavigatorWatcher.js:73:21)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ...postbuild: `react-snap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ...  postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by stereobooster** [comment] 2018-06-25 09:39
Duplicate of https://github.com/stereobooster/react-snap/issues/131

**Closed by stereobooster** 2018-06-25 09:39 UTC

**Comment by mehrdadkhan64** [comment] 2018-06-25 10:47
hi 
it's not duplicate. in my case it work good but when i remove service worker from create react app, this error appear if i dont change service worker it work fine why?

**Comment by stereobooster** [comment] 2018-06-25 10:49
because some resources are accessible with SW and not accessible without it. The main issue here is rather UX - you can not see what caused an error, in this sense this is duplicate

**Comment by mehrdadkhan64** [comment] 2018-06-25 11:11
can i use react-snap without sw?
i need to hide source code of my web thanks.

**Comment by stereobooster** [comment] 2018-06-25 11:29
> can i use react-snap without sw?

Yes you can. SW in this case hides another bug

**Comment by mehrdadkhan64** [comment] 2018-06-25 12:09
why i see all files in dev tools? i think ssr must hide my source code. how i must hide my source code with [react-snap?
![untitled](https://user-images.githubusercontent.com/39912171/41849356-e190ba44-7895-11e8-87c1-d5025269c755.png)

i want hide my website source code, and i use SSR with react-snap for it but i ssee that it can not be done why? please guide me in  correct direction

**Comment by stereobooster** [comment] 2018-06-25 12:16
I'm not sure what you want to achieve. Maybe you want to remove JS map files? Also you can try `"reactSnap": { "removeScriptTags": true }` but not sure this is what you want.

**Comment by mehrdadkhan64** [comment] 2018-06-25 13:58
When I deploy a react application anyone can inspect element and see the source code so anyone can copy my react web app. How to avoid this?

**Comment by stereobooster** [comment] 2018-06-25 14:10
Generally you can not. You can obfuscate code, but this is not actually hiding your code. This is how web works in general - JS transmitted to the client. You can remove to `*.js.map`, this is the most closest thing to what you want. If you want to hide logic move it to the server side

**Comment by mehrdadkhan64** [comment] 2018-06-25 14:17
ok i do it but i see entire project in dev tools! how i transfer logic to server side with react-snap?
how i do all of my logic in a app.js file in the server side and then send results to client? without they can see my code?

**Comment by mehrdadkhan64** [comment] 2018-06-25 14:30
i need 
render(){
...
}
and want user cant see what on the ...

**Comment by stereobooster** [comment] 2018-06-25 14:40
> how i transfer logic to server side with react-snap?

This is not the purpose of the react-snap. Take a look into something else - Node.js, Ruby on Rails etc

**Comment by mehrdadkhan64** [comment] 2018-06-25 15:27
> can i use react-snap without sw?

> Yes you can. SW in this case hides another bug
how i can 
i can't when i remove it i give error
i have not any idea about how use react-snap without SW 
thanks a lot
thanks
